apiVersion: v1
kind: Deployment
metadata:
  name: warehouse_service
spec:
  selector:
    matchLabels:
      app: warehouse_service
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1

  template:
    metadata:
      labels:
        app: warehouse_service
    spec:
      containers:
      - name: warehouse-project
        image: lolverae/warehouse_service
        imagePullPolicy: Always
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Deployment
metadata:
  name: warehouse_service
spec:
  selector:
    matchLabels:
      app: warehouse_service
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1

  template:
    metadata:
      labels:
        app: warehouse_service
    spec:
      containers:
      - name: warehouse-project
        image: lolverae/warehouse_service
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
