version: '3.0'

services:
  web:
    image: lolverae/warehouse_service:latest
    ports: 
      - "8000:8000"
    env_file:
      - .env
    restart: always
    
    deploy:
      replicas: 2
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: always
  couch:
    image: couchdb
    volumes:
      - db-data:/var/lib/couchdb/data
    env_file:
      - .env
    restart: always
    ports:
      - "5984:5984"
    deploy:
      replicas: 2
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: always


volumes:
  db-data:
