version: '3.0'

services:
  web:
    image: lolverae/warehouse_service:latest
    ports: 
      - "8000:8000"
    env_file:
      - .env
    restart: always

  couch:
    image: couchdb
    volumes:
      - db-data:/var/lib/couchdb/data
    env_file:
      - .env
    restart: always
    ports:
      - "5984:5984"

volumes:
  db-data:
