apiVersion: apps/v1
kind: Deployment
metadata:
  name: warehouse-db
spec:
  selector:
    matchLabels:
      app: warehouse-db
  replicas: 1
  template:
    metadata:
      labels:
        app: warehouse-db
    
    spec:
      containers:
      - name: couchdb
        image: couchdb:2.3
        env:
        - name: SECRET_USERNAME
        valueFrom:
          secretKeyRef:
            name: ADMIN_USERNAME
            key: COUCHDB_USER
        - name: SECRET_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ADMIN_PASSWORD
              key: COUCHDB_PASSWORD
        ports:
        - containerPort: 5984
        volumeMounts:
        - name: couchdb-persistent-storage
          mountPath: /var/lib/couchdb
      volumes:
      - name: couchdb-persistent-storage
        persistentVolumeClaim:
          claimName: couchdb-pv-claim