apiVersion: apps/v1
kind: Deployment
metadata:
  name: warehouse-db
  namespace: warehouse-ns
spec:
  selector:
    matchLabels:
      app: warehouse-db
  replicas: 1
  template:
    metadata:
      labels:
        app: warehouse-db
    
    spec:
      containers:
      - name: couchdb
        image: couchdb:2.3
        env:
        - name: COUCHDB_USER
          valueFrom:
            secretKeyRef:
              name: db-user-pass
              key: username
        - name: COUCHDB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-user-pass
              key: password
        - name: COUCH_HOST
          value: "warehouse-db"
        - name: COUCH_PORT
          value: "5984"
        ports:
        - containerPort: 5984
        volumeMounts:
        - name: couchdb-persistent-storage
          mountPath: /var/lib/couchdb
      volumes:
      - name: couchdb-persistent-storage
        persistentVolumeClaim:
          claimName: couchdb-pv-claim