---
- name: Push latest {{image_name}}
  run_once: true
  command: "docker push {{ image_name }}:latest"
  delegate_to: localhost


- name: Push version {{image_name}}
  run_once: true
  command: "sudo docker push {{ image_name }}:{{ image_version }}"
  delegate_to: localhost