---
- name: Check if Image exists {{image_name}}
  run_once: true
  shell:
    _raw_params: "docker image history {{ image_name }}:{{ image_version }} | wc -l"
  delegate_to: localhost
  register: image_exists
  changed_when: false

- name: Print current image {{image_name}}
  run_once: true
  debug:
    msg: "Building image: {{ image_name }}"

- name: Build the Image {{image_name}}
  run_once: true
  docker_image:
    path: /home/alberto/warehouse_service/app
    name: "{{ image_name }}"
    tag: "{{ image_version }}"
    pull: true
  when:
  - image_exists.stdout == "0"