---
- name: Check if Image exists {{image_name}}
  run_once: true
  shell:
    _raw_params: "sudo docker image history {{ image_name }}:{{ image_version }} | wc -l"
  delegate_to: localhost
  register: tag_image_exists
  changed_when: false

- name: fail {{image_name}}
  run_once: true
  fail:
    msg: "Image does not exist {{ image_name }}:{{ image_version }}"
  when:
  - tag_image_exists.stdout == "0"

- name: Tag latest {{image_name}}
  run_once: true
  shell:
    _raw_params: "sudo docker tag {{ image_name }}:{{ image_version }} {{ image_name }}:{{ item }}"
  delegate_to: localhost
  with_items:
  - "latest"
  when:
  - tag_image_exists.stdout != "0"

