---

- name: Build Image {{build_and_push_image_name}}
  import_tasks: image-build.yml

- name: Tag Image {{build_and_push_image_name}}
  import_tasks: image-tag.yml

- name: Push Image {{build_and_push_image_name}}
  import_tasks: image-push.yml